// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repositories.Data;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(Task6DbContext))]
    partial class Task6DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.Property<int?>("Typeid")
                        .HasColumnType("integer")
                        .HasColumnName("typeid");

                    b.HasKey("Id")
                        .HasName("elements_pkey");

                    b.HasIndex("Typeid");

                    b.ToTable("elements", (string)null);
                });

            modelBuilder.Entity("Models.Elementtype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("elementtypes_pkey");

                    b.ToTable("elementtypes", (string)null);
                });

            modelBuilder.Entity("Models.Presentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("author");

                    b.Property<string>("Title")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("title")
                        .HasDefaultValueSql("'Title'::character varying");

                    b.HasKey("Id")
                        .HasName("presentations_pkey");

                    b.ToTable("presentations", (string)null);
                });

            modelBuilder.Entity("Models.Sharedpresentationslide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Presentationid")
                        .HasColumnType("integer")
                        .HasColumnName("presentationid");

                    b.Property<int?>("Slideid")
                        .HasColumnType("integer")
                        .HasColumnName("slideid");

                    b.HasKey("Id")
                        .HasName("sharedpresentationslides_pkey");

                    b.HasIndex("Slideid");

                    b.HasIndex(new[] { "Presentationid", "Slideid" }, "sharedpresentationslides_presentationid_slideid_idx");

                    b.ToTable("sharedpresentationslides", (string)null);
                });

            modelBuilder.Entity("Models.Sharedslideelement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ElementContent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("element_content")
                        .HasDefaultValueSql("''::text");

                    b.Property<int?>("ElementHeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("element_height");

                    b.Property<int?>("ElementWidth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("element_width");

                    b.Property<int?>("ElementX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("element_x");

                    b.Property<int?>("ElementY")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("element_y");

                    b.Property<int?>("Elementid")
                        .HasColumnType("integer")
                        .HasColumnName("elementid");

                    b.Property<int?>("Slideid")
                        .HasColumnType("integer")
                        .HasColumnName("slideid");

                    b.HasKey("Id")
                        .HasName("sharedslideelements_pkey");

                    b.HasIndex("Elementid");

                    b.HasIndex(new[] { "Slideid", "Elementid" }, "sharedslideelements_slideid_elementid_idx");

                    b.ToTable("sharedslideelements", (string)null);
                });

            modelBuilder.Entity("Models.Slide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Background")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("background")
                        .HasDefaultValueSql("'white'::character varying");

                    b.HasKey("Id")
                        .HasName("slides_pkey");

                    b.ToTable("slides", (string)null);
                });

            modelBuilder.Entity("Models.Element", b =>
                {
                    b.HasOne("Models.Elementtype", "Type")
                        .WithMany("Elements")
                        .HasForeignKey("Typeid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("elements_typeid_fkey");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Models.Sharedpresentationslide", b =>
                {
                    b.HasOne("Models.Presentation", "Presentation")
                        .WithMany("Sharedpresentationslides")
                        .HasForeignKey("Presentationid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("sharedpresentationslides_presentationid_fkey");

                    b.HasOne("Models.Slide", "Slide")
                        .WithMany("Sharedpresentationslides")
                        .HasForeignKey("Slideid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("sharedpresentationslides_slideid_fkey");

                    b.Navigation("Presentation");

                    b.Navigation("Slide");
                });

            modelBuilder.Entity("Models.Sharedslideelement", b =>
                {
                    b.HasOne("Models.Element", "Element")
                        .WithMany("Sharedslideelements")
                        .HasForeignKey("Elementid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("sharedslideelements_elementid_fkey");

                    b.HasOne("Models.Slide", "Slide")
                        .WithMany("Sharedslideelements")
                        .HasForeignKey("Slideid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("sharedslideelements_slideid_fkey");

                    b.Navigation("Element");

                    b.Navigation("Slide");
                });

            modelBuilder.Entity("Models.Element", b =>
                {
                    b.Navigation("Sharedslideelements");
                });

            modelBuilder.Entity("Models.Elementtype", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("Models.Presentation", b =>
                {
                    b.Navigation("Sharedpresentationslides");
                });

            modelBuilder.Entity("Models.Slide", b =>
                {
                    b.Navigation("Sharedpresentationslides");

                    b.Navigation("Sharedslideelements");
                });
#pragma warning restore 612, 618
        }
    }
}
